UnityTalk/Controllers/MemberController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UnityTalk.Models;

namespace VirtualMeeting.Controllers
{
    public class MemberController : Controller
    {
        UnityTalkEntities8 ut2 = new UnityTalkEntities8();
        // GET: Member
        public ActionResult ViewGroup()
        {
            return View(ut2.GroupTables.ToList());

        }

        public ActionResult ViewMember()
        {
            return View(ut2.GroupMemberTables.ToList());

        }

        public ActionResult Search_Group(string search)
        {
            
            return View(ut2.GroupTables.Where(x => x.GrpName.Contains(search) || search == null).ToList());
        }

        public ActionResult Search_Member(string search)
        {
            return View(ut2.GroupMemberTables.Where(x => x.UserTable.UserName.Contains(search) || search == null).ToList());

        }

    }
}

UnityTalk/Views/Member/Search_Group.cshtml
@model IEnumerable<UnityTalk.Models.GroupTable>
@{ 
    Layout = null;
}
<br />
<br />


<table class="table table-striped" border="1">
    <thead>
        <tr>
            <th>GrpName</th>
            <th>GrpDescp</th>
            <th>GrpMode</th>
            <th>User Name</th>
        </tr>
    </thead>
    <tbody>
        @if (Model.Count() == 0)
        {
            <tr>
                <td colspan="4" style="color:red">
                    No Match
                </td>
            </tr>
        }
        else
        {
            foreach (var item in Model)
            {
                <tr>
                    <th>@Html.DisplayFor(model => item.GrpName)</th>
                    <th>@Html.DisplayFor(model => item.GrpDescp)</th>
                    <th>

                        @if (item.GrpMode)
                        {


                            <p>Public</p>
                        }
                        else
                        {
                            <p>Private</p>
                        }
                    </th>
                    <th>@Html.DisplayFor(model => item.UserTable.UserName)</th>
                </tr>
            }
        }

    </tbody>
</table>

<div>
    @Html.ActionLink("Back", "ViewGroup", "Member")
</div>

UnityTalk/Views/Member/Search_Member.cshtml
@model IEnumerable<UnityTalk.Models.GroupMemberTable>
@{ 
    Layout = null;
}
<br />
<br />


<table class="table table-striped" border="1">
    <thead>
        <tr>
            <th>GrpName</th>
            <th>UserName</th>
        </tr>
    </thead>
    <tbody>
        @if (Model.Count() == 0)
        {
            <tr>
                <td colspan="4" style="color:red">
                    No Match
                </td>
            </tr>
        }
        else
        {
            foreach (var item in Model)
            {
                <tr>
                    <th>@Html.DisplayFor(model => item.UserTable.UserName)</th>
                    <th>@Html.DisplayFor(model => item.GroupTable.GrpName)</th>
                    
                </tr>
            }
        }

    </tbody>
</table>

<div>
    @Html.ActionLink("Back", "ViewMember", "Member")
</div>

UnityTalk/Views/Member/ViewGroup.cshtml
@model IEnumerable<UnityTalk.Models.GroupTable>

@{
    ViewBag.Title = "ViewGroup";
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <img src="~/Content/assets/Images/logo.png" height="45px" style="margin-left:20px;" />
        <div class="container">

            @Html.ActionLink("UnityTalk", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })

        </div>
    </nav>



    <h2>ViewGroup</h2>

    <p>
        @Html.ActionLink("Back", "Dashboard", "Admin")
    </p>

    @using (Html.BeginForm("Search_Group", "Member", FormMethod.Get))
    {
        @Html.TextBox("search")
        <input type="submit" value="Search Group" />
    }

    <table class="table table-striped" border="1">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.GrpName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.GrpDescp)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.GrpMode)
            </th>

            <th>
                @Html.DisplayNameFor(model => model.UserTable.UserName)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.GrpName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.GrpDescp)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.GrpMode)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.UserTable.UserName)
                </td>

            </tr>
        }

    </table>


    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")

</body>
</html>

UnityTalk/Views/Member/ViewMember.cshtml
@model IEnumerable<UnityTalk.Models.GroupMemberTable>

@{
    ViewBag.Title = "ViewMember";
    Layout = null;
}


<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <img src="~/Content/assets/Images/logo.png" height="45px" style="margin-left:20px;" />
        <div class="container">

            @Html.ActionLink("UnityTalk", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

        </div>
    </nav>




    <h2>ViewMember</h2>
    <p>
        @Html.ActionLink("Back", "Dashboard", "Admin")
    </p>


    @using (Html.BeginForm("Search_Member", "Member", FormMethod.Get))
    {
        @Html.TextBox("search")
        <input type="submit" value="Search Member" />

    }

    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.GroupTable.GrpName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.UserTable.UserName)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.GroupTable.GrpName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.UserTable.UserName)
                </td>

            </tr>
        }

    </table>





    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")

</body>
</html>