UnityTalk/Models/FeedBackTable.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnityTalk.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeedBackTable
    {
        public int FeedbackId { get; set; }
        public int Rating { get; set; }
        public string cont { get; set; }
        public System.DateTime Date { get; set; }
        public int UserId { get; set; }
    
        public virtual UserTable UserTable { get; set; }
    }
}

UnityTalk/Controllers/FeedBackController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UnityTalk.Models;

namespace UnityTalk.Controllers
{
    public class FeedBackController : Controller
    {
        UnityTalkEntities8 dbF = new UnityTalkEntities8();

        [HttpGet]
        public ActionResult feedback()
        {
            if (Session["Id"] == null)
            {
                return RedirectToAction("UserNotFound", "Home", new { msg = "It seems You haven't sign in yet !" });
            }

            UserTable user = dbF.UserTables.Find(Session["Id"]);
            if (user == null)
            {
                TempData["Error"] = "Someting is Wrong !!";
            }

            FeedBackTable fb = dbF.FeedBackTables.FirstOrDefault(a => a.UserId == user.Uid);

            if (fb == null)
            {
                return View();
            }
            else
            {
                return View(fb);
            }
        }
        [HttpPost]
        public ActionResult feedback(FeedBackTable fb)
        {
            if (Session["Id"] == null)
            {
                return RedirectToAction("UserNotFound", "Home", new { msg = "It seems You haven't sign in yet !" });
            }

            UserTable user = dbF.UserTables.Find(Session["Id"]);
            if (user == null)
            {
                TempData["Error"] = "Someting is Wrong !!";
            }

            FeedBackTable userfb = dbF.FeedBackTables.FirstOrDefault(a => a.UserId == user.Uid);

            if (userfb == null)
            {
                if(fb.Rating == 0)
                {
                    TempData["Error"] = "Please Give atleast 1 star to rate!!";
                    ModelState.Clear();
                    return RedirectToAction("feedback");
                }
                else
                {
                    FeedBackTable newfb = new FeedBackTable();
                    newfb.Rating = fb.Rating;
                    newfb.Date = DateTime.Today;
                    newfb.cont = fb.cont;
                    newfb.UserId = user.Uid;

                    dbF.FeedBackTables.Add(newfb);
                    dbF.SaveChanges();
                    TempData["Success"] = "Thank You For Your Valuable Feedback!!";
                    return RedirectToAction("feedback");
                }
            }
            else
            {

                userfb.Date = DateTime.Today;
                userfb.Rating = fb.Rating;
                userfb.cont = fb.cont;
                dbF.Entry(userfb).State = System.Data.Entity.EntityState.Modified;
                dbF.SaveChanges();
                TempData["Success"] = "Thank You For Update Your Valuable Feedback!!";
                return RedirectToAction("feedback");
            }
        }
    }
}

UnityTalk/Views/FeedBack/feedback.cshtml
@model UnityTalk.Models.FeedBackTable

@{
    ViewBag.Title = "feedback";
}

<head>
    <link rel="stylesheet" href="~/Content/css/feedback.css" />
</head>
<body>
    <div class="ratingDivHeight">
        <div class="Rating-div">
            <h3>Please kindly Rate Us</h3>
            <form action="@Url.Action("feedback","FeedBack")" method="post">
                <div class="rating-input-div">
                    @Html.HiddenFor(model => model.Rating)
                    <i class='bx bx-star star' style="--i: 0;"></i>
                    <i class='bx bx-star star' style="--i: 1;"></i>
                    <i class='bx bx-star star' style="--i: 2;"></i>
                    <i class='bx bx-star star' style="--i: 3;"></i>
                    <i class='bx bx-star star' style="--i: 4;"></i>
                </div>
                <div class="OpinionText">
                    <p>Please share with us your experience</p>
                </div>
                @Html.TextAreaFor(model => model.cont, new { htmlAttributes = new { @class = "form-control" ,
               cols = "30", rows = "5", placeholder = "Your opinion..." } })
               
                <div class="FileUploadCancelDiv" >
                    <button class="FileUploadbtn" type="submit">
                        <p>Submit</p>
                    </button>
                    <button class="FileUploadbtn FileUploadCancelBtn" type="button">
                        <p>Cancel</p>
                    </button>
                </div>
            </form>
        </div>
    </div>
    @section scripts {

        <script>
            document.addEventListener('DOMContentLoaded', function () {

                let activeNavLinks = document.querySelectorAll('.nav-link.active');

                activeNavLinks.forEach(function (link) {
                    link.classList.remove('active');
                });
                let dashboardElement = document.querySelector('.navFeed-l');

                if (dashboardElement) {
                    dashboardElement.classList.add('active');
                }
            });
        </script>

        <script src="~/Content/js/feedback.js"></script>


    }
    </body>





































    @*@using (Html.BeginForm())
    {
        

        <div class="form-horizontal">
            <h4>FeedBackTable</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.FeedbackId)

            <div class="form-group">
                @Html.LabelFor(model => model.Rating, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Rating, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Rating, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.cont, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.cont, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.cont, "", new { @class = "text-danger" })
                </div>
            </div>





            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>*@