UnityTalk/Controllers/ImageController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UnityTalk.Models;

namespace VirtualMeeting.Controllers
{
    public class ImageController : Controller
    {
        UnityTalkEntities8 ut3 = new UnityTalkEntities8();
        
        public ActionResult UploadImage()
        {
            if (Session["fit"] == null)
            {
                return RedirectToAction("UserNotFound", "Home", new { msg = "It seems You haven't sign in yet !" });
            }
            return View();
        }


        [HttpPost]
        public ActionResult UploadImage(HttpPostedFileBase file, GroupImgTable image)
        {

            if (file != null && file.ContentLength > 0)
            {
          
                string fileName = Path.GetFileNameWithoutExtension(file.FileName);

               

                fileName = fileName + DateTime.Now.ToString("YYmmssff") + Path.GetExtension(file.FileName);

                var savePath = Path.Combine(Server.MapPath("~/Content/assets/GroupImages"), fileName);

                file.SaveAs(savePath);

                image.GrpImgPath = $"/Content/assets/GroupImages/{fileName}";


                 
                ut3.GroupImgTables.Add(image);
                ut3.SaveChanges();

                ViewBag.Mssg1 = "Image has been uploaded!";

            }
            else
            {
                ViewBag.Mssg2 = "Image is not uploaded!";

            }

            return View();
        }

        public ActionResult ViewImage()
        {
            return View(ut3.GroupImgTables.ToList());
        }

        public ActionResult Search(string search)
        {
            return View(ut3.GroupImgTables.Where(x => x.ImgName.Contains(search) || search == null).ToList());
        }
        

        public ActionResult Delete(int? id)
        {   
            if (id == null)
            {
                ViewBag.not = "Id cant be null";
            }
            else
            {
                GroupImgTable grpImg = ut3.GroupImgTables.Find(id);
                string fullPath = grpImg.GrpImgPath;
                fullPath = Path.Combine(Server.MapPath(fullPath));
                if (System.IO.File.Exists(fullPath))
                {
                    System.IO.File.Delete(fullPath);

                }
                else
                {
                    ViewBag.Message = "File not found.";
                }
            }

            //string fullPath = $"~{ebookId.Path}";

            //string coverPath = ebookId.CoverPath;

            //coverPath = Path.Combine(Server.MapPath(coverPath));
            GroupImgTable grpImgId = ut3.GroupImgTables.Find(id);

            ut3.GroupImgTables.Remove(grpImgId);
            ut3.SaveChanges();


            return RedirectToAction("ViewImage");

        }



    }
}

UnityTalk/Views/Image/Search.cshtml
@model IEnumerable<UnityTalk.Models.GroupImgTable>
@{ 
    Layout = null;
}
<br/><br/>


<table class="table table-striped" border="1">
    <thead>
        <tr>
            <th>ImgName</th>
            <th>GrpImgPath</th>
        </tr>
    </thead>
    <tbody>
        @if(Model.Count() == 0)
            {
                <tr>
                    <td colspan="2" style="color:red">
                        No Match
                    </td>
                </tr>
        }
        else
        {
            foreach(var item in Model)
                {
    <tr>
        <td>@item.ImgName</td>
        <td>
            <img src="@Url.Content(item.GrpImgPath)" style="height:200px" />
        </td>


    </tr>
                }
        }
        
    </tbody>
</table>

<div>
    @Html.ActionLink("Back", "ViewImage", "Image")
</div>

UnityTalk/Views/Image/UploadImage.cshtml
@model UnityTalk.Models.GroupImgTable
@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <img src="~/Content/assets/Images/logo.png" height="45px" style="margin-left:20px;" />
        <div class="container">

            @Html.ActionLink("UnityTalk", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

        </div>
    </nav>



    <div class="container body-content">


        @using (Html.BeginForm("UploadImage", "Image", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {

            @Html.AntiForgeryToken()



            <div class="form-horizontal">
                <h4>Ebook Upload</h4>
                <hr />


                Banner Name
                @Html.EditorFor(model => model.ImgName, new { htmlAttributes = new { @class = "form-control" } })

                <div class="form-group">
                    @Html.Label("Select Ebook File", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <input type="file" name="file" />
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Upload" class="btn btn-default" />
                        @{
                            if (ViewBag.Mssg1 != null)
                            {
                                @ViewBag.Mssg1
                            }
                            else
                            {
                                @ViewBag.Mssg2
                            }


                        }

                    </div>
                </div>

            </div>

            <div>
                @Html.ActionLink("Back", "Dashboard", "Admin")
            </div>
        }

        <hr />

    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")

</body>
</html>

UnityTalk/Views/Image/ViewImage.cshtml
@model IEnumerable<UnityTalk.Models.GroupImgTable>

@{
    ViewBag.Title = "ViewImage";
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <img src="~/Content/assets/Images/logo.png" height="45px" style="margin-left:20px;" />
        <div class="container">

            @Html.ActionLink("UnityTalk", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

        </div>
    </nav>

    <h2>ViewImage</h2>

    <p>
        @Html.ActionLink("Back", "Dashboard", "Admin")
    </p>

    @using (Html.BeginForm("Search", "Image", FormMethod.Get))
    {
        @Html.TextBox("search")
        <input type="submit" value="Search" />
    }

    <table class="table table-striped" border="1">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ImgName)
            </th>

            <th>
                @Html.DisplayNameFor(model => model.GrpImgPath)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.ImgName)
                </td>
                <td>
                    <img src="@Url.Content(item.GrpImgPath)" style="height:200px" />
                </td>
                <td>
                    <a class="btn btn-outline-primary" href="@item.GrpImgPath">
                        Open
                    </a>

                    <a class="btn btn-outline-primary" href="@Url.Action("Delete", "Image", new {id = item.GrpImgId})">
                        Delete
                    </a>

                    @{
                        if (ViewBag.Message != null)
                        {
                            @ViewBag.Message
                        }
                    }

                </td>
            </tr>
        }

    </table>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")

</body>
</html>